### ISSUE TITLE
isso deveria ter uma logo

### ISSUE THREAD

**Issue by lucasfariaslf** [alunos-mestrado-emap/forum#1]
pensei na da emap, mas pode gerar problema de copyright. o que nao dá é esse avatar do git, yikes. o do dama, será?

**Comment by odanoburu** [comment]
exato, da emap não rola..

e o dama não sei, a princípio não fazemos parte..

será que alguém quer fazer uma montagem? :tongue:

**Comment by alsombra** [comment]
Eu fiz uma aqui pro Alunos-Mestrado-Emap. Entrem em [aqui](https://www.dropbox.com/s/60pccg5zhnpgtor/Logomakr_0NgKzZ.png?dl=0) e digam o que acharam. 
Obs: Pode-se editar [aqui](logomakr.com/0NgKzZ)

**Comment by odanoburu** [comment]
por mim, botamos essa! e ainda ficou imperativa (ame!)

**Comment by lucasfariaslf** [comment]
Antonio Amoroso. Igual por mim.

**Comment by odanoburu** [comment]
reabrindo pq o github não curtiu as dimensões da logo

**Comment by alsombra** [comment]
Esse [aqui](https://www.dropbox.com/s/y7cwrz68ni309b4/Logomakr_8JFLZM.png?dl=0) deve estar ok.

**Comment by odanoburu** [comment]
boa! mudei e está propagando
